### ISSUE TITLE
How to create a directory in python code

### ISSUE THREAD

**Issue by gggkevin** [QQxiaoming/QCustomFileSystemModel#1]
Excuse me, now I want to create a directory and delete a directory in the QNativeFileSystemModel class, how do I do that?

**Comment by QQxiaoming** [comment]
Hi @gggkevin, Try my latest code, can it solve your needs? https://github.com/QQxiaoming/QCustomFileSystemModel/commit/fec21bfdb6569cdf58e97113ae98e06944912ee1#diff-ecd5501669ac91a68f982f57bfc41b8edb1e182d3db46304073ece526169b57c

**Comment by gggkevin** [comment]
Thanks a lot! It really helped me this time!
